[package]
name = "ModelSpaceShipRender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.27.0"
nalgebra-glm = "0.19.0"
tobj = "4.0.2"
